<?php $crumbs = $block->getCrumbsStore(); ?>
<?php if ($crumbs && is_array($crumbs)) : ?>
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="bs-col-md-12">
                    <div class="breadcrumbs">
                        <ul class="items">
                            <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                                <li class="item <?= /* @escapeNotVerified */ $crumbName ?>">
                                    <?php if ($crumbInfo['link']) : ?>
                                        <a href="<?= /* @escapeNotVerified */ $crumbInfo['link'] ?>" title="<?= $block->escapeHtml($crumbInfo['title']) ?>"><?= $block->escapeHtml($crumbInfo['label']) ?></a>
                                    <?php else: ?>
                                        <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
                                    <?php endif; ?>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
