<div class="container-fluid fifth-row">
    <div class="container">
        <div class="row">
            <div class="bs-col-md-12">
                <div class="copyright">
                    <div class="">
                        <?= __('Bricoman Italia S.r.l. - Single-member company, Registered and Administrative Office: Via G. Marconi, 24 Rozzano (MI) Italy 20089 Cap.Soc. € 65,000,000.00 i.v.
Companies Register MI - C.F. and VAT number no. 05602670969 - R.E.A. n ° 1833919, Subject to the management and coordination of S.I.B. - Società Italiana Bricolage S.p.A.'); ?>
                    </div>
                    <div class="">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>