<div class="container-fluid fifth-row">
    <div class="container">
        <div class="row">
            <div class="bs-col-md-12">
                <div class="copyright">
                    <div class="">
                        <?= ("Stocktech s.r.l.s. VAT 12345678900 | Powered by Stocktech"); ?>
                    </div>
                    <div class="">
                        <?= __("All logos and trademarks are the property of their respective manufacturers - © Copyright 2019 STOCKTECH.IT, All rights reserved"); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>