<?php
// @codingStandardsIgnoreFile

/** @var $block Walan\StoreLocator\Block\View\StoreList */


$listOfStores = $this->listOfStores();

$orderedList = $this->getOrderedListStores($listOfStores);

$lung = count($orderedList);
$numColumn = 4;
$mod = $lung % $numColumn;
$numElemForCol = round (($lung / $numColumn));
$newCol = $numElemForCol;

?>

<?php if ($listOfStores): ?>

    <div id="bm_shop" class="row stores">
        <div class="bs-col-sm-12">
            <div class="stores__title"><?= __('All our stores'); ?></div>
        </div>
    </div>
    <div id="bm_div-shop" class="row list-stores">
        <div class="bs-col-md-12">
            <div class="row">
                <div class="bs-col-sm-3 bs-col-xs-12">
                    <?php for($i=0; $i<$lung; $i++){
                    $elem = $orderedList[$i];
                    ?>
                    <?php if ($newCol>0):?>

                        <div class="bm_container-link">
                            <a class="bm_link" href="<?= $elem['url'] ?? ''; ?>"> <?= $elem['name'] ?? ''; ?> </a>
                        </div>

                        <?php $newCol--; endif; ?>

                    <?php if ($newCol == 0): ?>

                    <?php if ($mod > 0): $i++;
                        $newElem = $orderedList[$i];
                        ?>

                        <div class="bm_container-link">
                            <a class="bm_link" href="<?= $newElem['url'] ?? ''; ?>"> <?= $newElem['name'] ?? ''; ?> </a>
                        </div>

                        <?php $mod--; endif; ?>

                </div>
                <div class="bs-col-sm-3 bs-col-xs-12">
                    <?php $newCol = $numElemForCol; endif; ?>

                    <?php }  ?>
                </div>
            </div>

        </div>
    </div>

<?php endif; ?>