<div class="container">
	<div class="row">
	    <div class="bs-col-sm-12">
	        <div class="bm_not-found">

	            <div class="bm_not-found__text">
	                <?= __('We are sorry'); ?>
	            </div>

	            <div class="bm_not-found__img">
	            </div>

	            <div class="bm_not-found__text">
	                <?= __('there was a problem'); ?>
	            </div>

	        </div>

	    </div>
	</div>

</div>

<!--@TODO: riscrivere meglio qui -->
<div class="container-fluid" style="background: #f4f7f8">
    <div class="container">
        <div class="row">

            <div class="bs-col-md-12" style="padding: 0px;">
                <div class="bm_most-searched-categories">
                    <div class="bm_most-searched-categories__title">
                        <?= __('Our most searched categories'); ?>
                    </div>
                    <div class="row">
                        <div class="bs-col-lg-3 bs-col-sm-6 bs-col-xs-12">
                            <div class="bm_category-searched">
                                <div class="bm_category-searched__top-img" style="background-image: url('<?php echo $this->getViewFileUrl('images/testimg.png'); ?>'">
                                </div>

                                <div class="bm_category-searched__text">
                                    <div class="bm_title-category-searched">
                                        ferramenta
                                    </div>
                                    <div class="bm_category-searched-container">
                                        <a class="bm_category-searched-container__link">
                                            <span> Scaffali </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                        <a class="bm_category-searched-container__link">
                                            <span> Segnaletica </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                        <a class="bm_category-searched-container__link">
                                            <span> Carrucole e Puleggie </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                        <a class="bm_category-searched-container__link">
                                            <span> Cassette postali </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                    </div>
                                </div>

                            </div>
                        </div>

                        <div class="bs-col-lg-3 bs-col-sm-6 bs-col-xs-12">
                            <div class="bm_category-searched">
                                <div class="bm_category-searched__top-img" style="background-image: url('<?php echo $this->getViewFileUrl('images/testimg.png'); ?>'">
                                </div>

                                <div class="bm_category-searched__text">
                                    <div class="bm_title-category-searched">
                                        ferramenta
                                    </div>
                                    <div class="bm_category-searched-container">
                                        <a class="bm_category-searched-container__link">
                                            <span> Scaffali </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                        <a class="bm_category-searched-container__link">
                                            <span> Segnaletica </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                        <a class="bm_category-searched-container__link">
                                            <span> Carrucole e Puleggie </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                        <a class="bm_category-searched-container__link">
                                            <span> Cassette postali </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                    </div>
                                </div>

                            </div>
                        </div>

                        <div class="bs-col-lg-3 bs-col-sm-6 bs-col-xs-12">
                            <div class="bm_category-searched">
                                <div class="bm_category-searched__top-img" style="background-image: url('<?php echo $this->getViewFileUrl('images/testimg.png'); ?>'">
                                </div>

                                <div class="bm_category-searched__text">
                                    <div class="bm_title-category-searched">
                                        ferramenta
                                    </div>
                                    <div class="bm_category-searched-container">
                                        <a class="bm_category-searched-container__link">
                                            <span> Scaffali </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                        <a class="bm_category-searched-container__link">
                                            <span> Segnaletica </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                        <a class="bm_category-searched-container__link">
                                            <span> Carrucole e Puleggie </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                        <a class="bm_category-searched-container__link">
                                            <span> Cassette postali </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                    </div>
                                </div>

                            </div>
                        </div>

                        <div class="bs-col-lg-3 bs-col-sm-6 bs-col-xs-12">
                            <div class="bm_category-searched">
                                <div class="bm_category-searched__top-img" style="background-image: url('<?php echo $this->getViewFileUrl('images/testimg.png'); ?>'">
                                </div>

                                <div class="bm_category-searched__text">
                                    <div class="bm_title-category-searched">
                                        ferramenta
                                    </div>
                                    <div class="bm_category-searched-container">
                                        <a class="bm_category-searched-container__link">
                                            <span> Scaffali </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                        <a class="bm_category-searched-container__link">
                                            <span> Segnaletica </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                        <a class="bm_category-searched-container__link">
                                            <span> Carrucole e Puleggie </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                        <a class="bm_category-searched-container__link">
                                            <span> Cassette postali </span>
                                            <span class="bm-icon-arrow-right bm_category-icon"></span>
                                        </a>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>