<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer3-container">
			<div class="footer3">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_copyright')->toHtml();?>	
			<div class="copyright">
					<?= /* @escapeNotVerified */ $block->getCopyright() ?>
				</div>
				<div class="clearer"></div>
		    </div>
		</div>
