<?php
/**
 * @package Thinkopen
 * @author Paolo
 */

// @codingStandardsIgnoreFile

/** @var Thinkopen\CustomerCustomAttributes\Block\Form $block */
?>
<form class="form form-edit-account" action="<?= /* @escapeNotVerified */ $block->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= /* @escapeNotVerified */ __('* Required Fields') ?>" autocomplete="off">
    <fieldset class="fieldset info">
        <div class="container__change-password">
            <?= $block->getBlockHtml('formkey') ?>
            <legend class="legend"><span><?= /* @escapeNotVerified */ __('Account Information') ?></span></legend><br>
            <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getCustomer())->toHtml() ?>

            <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
            <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
            <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
            <?php if ($_dob->isEnabled()): ?>
                <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
            <?php endif ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
            <?php endif ?>
            <?php if ($_gender->isEnabled()): ?>
                <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
            <?php endif ?>
        </div>
        <div class="field choice">
            <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1" title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>" class="checkbox" />
            <label class="label" for="change-email"><span><?= $block->escapeHtml(__('Change Email')) ?></span></label>
        </div>
        <div class="field choice">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"<?php if ($block->getChangePassword()): ?> checked="checked"<?php endif; ?> class="checkbox" />
            <label class="label" for="change-password"><span><?= $block->escapeHtml(__('Change Password')) ?></span></label>
        </div>

    </fieldset>

    <?= /* @noEscape */ $block->getChildHtml('form_fields_before_in_form') ?>

    <fieldset class="fieldset password" data-container="change-email-password">
        <div class="container__change-password">
            <legend class="legend"><span data-title="change-email-password"><?= /* @escapeNotVerified */ __('Change Email and Password') ?></span></legend><br>
            <div class="field email required" data-container="change-email">
                <label class="label" for="email"><span><?= /* @escapeNotVerified */ __('Email') ?></span></label>
                <div class="control">
                    <input type="email" autocomplete="email" name="email" id="email" data-input="change-email" value="<?= $block->escapeHtml($block->getCustomer()->getEmail()) ?>" title="<?= /* @escapeNotVerified */ __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
                </div>
            </div>
            <div class="field password current required">
                <label class="label" for="current-password"><span><?= /* @escapeNotVerified */ __('Current Password') ?></span></label>
                <div class="control">
                    <input type="password" class="input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
                </div>
            </div>
            <div class="field new password required" data-container="new-password">
                <label class="label" for="password"><span><?= /* @escapeNotVerified */ __('New Password') ?></span></label>
                <div class="control">
                    <input type="password" class="input-text" name="password" id="password"
                           data-password-min-length="<?= $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                           data-password-min-character-sets="<?= $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                           data-input="new-password"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           autocomplete="off" />
                    <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                        <div id="password-strength-meter" class="password-strength-meter">
                            <?= /* @escapeNotVerified */ __('Password Strength') ?>:
                            <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                <?= /* @escapeNotVerified */ __('No Password') ?>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="field confirm password required" data-container="confirm-password">
                <label class="label" for="password-confirmation"><span><?= /* @escapeNotVerified */ __('Confirm New Password') ?></span></label>
                <div class="control">
                    <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                           data-input="confirm-password"
                           autocomplete="off" />
                </div>
            </div>
            <?= $block->getChildHtml('form_additional_info') ?>
        </div>
    </fieldset>
    <fieldset>
        <?php $userDefinedAttributes = $block->getLayout()->getBlock('customer_form_user_attributes'); ?>
        <?php if ($userDefinedAttributes):?>
            <?php $userDefinedAttributes->setEntityType('customer')->setShowContainer(false);?>
            <?php $block->restoreSessionData($userDefinedAttributes->getMetadataForm());?>
            <?= $userDefinedAttributes->toHtml() ?>
        <?php endif;?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= /* @escapeNotVerified */ __('Save') ?>"><span><?= /* @escapeNotVerified */ __('Save') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= /* @escapeNotVerified */ __('Go back') ?></span></a>
        </div>
    </div>
</form>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        var ignore = <?= /* @escapeNotVerified */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

        dataForm.mage('validation', {
            <?php if ($_dob->isEnabled()): ?>
            errorPlacement: function(error, element) {
                if (element.prop('id').search('full') !== -1) {
                    var dobElement = $(element).parents('.customer-dob'),
                        errorClass = error.prop('class');
                    error.insertAfter(element.parent());
                    dobElement.find('.validate-custom').addClass(errorClass)
                        .after('<div class="' + errorClass + '"></div>');
                }
                else {
                    error.insertAfter(element);
                }
            },
            ignore: ':hidden:not(' + ignore + ')'
            <?php else: ?>
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
            <?php endif ?>
        });

    });
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= /* @escapeNotVerified */ __('Change Email') ?>",
                "titleChangePassword": "<?= /* @escapeNotVerified */ __('Change Password') ?>",
                "titleChangeEmailAndPassword": "<?= /* @escapeNotVerified */ __('Change Email and Password') ?>"
            }
        },
        "*": {
            "Thinkopen_CustomerCustomAttributes/validation": {
                "ignore": <?= (int) ($_dob->isEnabled() || $userDefinedAttributes->hasUserDefinedAttributes()) ?>,
                "hasUserDefinedAttributes": <?= (int) $userDefinedAttributes->hasUserDefinedAttributes() ?>,
                "isDobEnabled": <?= (int) $_dob->isEnabled() ?>,
                "mixins": [
                    "Thinkopen_CustomerCustomAttributes/error-placement",
                    "Thinkopen_CustomerCustomAttributes/validation-ignore"
                ]
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
<style>
    .customer-account-edit .column{
        background-color: #f7f7f7;
        padding: 24px;
    }
    .customer-account-edit .column .field-name-firstname,
    .customer-account-edit .column .field-name-lastname,
    .customer-account-edit .column .email,
    .customer-account-edit .column .current,
    .customer-account-edit .column .password,
    .customer-account-edit .column .confirm
    {
        width: 49%;
        display: inline-block;
    }
    .customer-account-edit .column fieldset.password{
        width: 100%;
    }
    .customer-account-edit .column #password-strength-meter-container{
        display: none !important;
    }
    .customer-account-edit .column #change-email,
    .customer-account-edit .column #change-password{
        margin-right: 10px;
        -webkit-appearance: none;
        -moz-appearance: none;
        width: 20px;
        height: 20px;
        border: 1px solid #5b5b5b;
        margin-bottom: 5px;
        background-color: #ffffff;
        cursor: pointer;
    }

    .customer-account-edit .column #change-email:checked + .label:before,
    .customer-account-edit .column #change-password:checked + .label:before{
        font-family: FontAwesome;
        content: "\f00c";
        position: absolute;
        top: 6.5px;
        left: 3.5px;
        color: #5b5b5b;
        font-size: 16px;
    }
    .customer-account-edit .column #change-password:checked + .label:before{
        top: 5.5px;
    }
    .customer-account-edit .column .label{
        margin-left: 10px;
        font-size: 12px;
        text-transform: uppercase;
        letter-spacing: 0.7px;
        margin-left: 10px;
    }
    .customer-account-edit .column .actions-toolbar .primary{
        text-align: right;
    }
    .customer-account-edit .column .actions-toolbar .primary button{
        border: 1px solid #000000;
        color: #ffffff;
        cursor: pointer;
        font-family: Lato, serif;
        font-size: 12px;
        font-weight: 400;
        letter-spacing: 0.5px;
        line-height: 30px;
        list-style-type: none;
        margin-bottom: 0px;
        text-align: center;
        text-shadow: none;
        background-color: #000000;
    }
    .customer-account-edit .column .actions-toolbar .secondary{
        display: none !important;
    }
    .customer-account-edit .column .password-info{
        display: none !important;
    }
    @media (max-width: 769px) {
        .customer-account-edit .column .field-name-firstname,
        .customer-account-edit .column .field-name-lastname,
        .customer-account-edit .column .email,
        .customer-account-edit .column .current,
        .customer-account-edit .column .password,
        .customer-account-edit .column .confirm {
            width: 100%;
        }
        .customer-account-edit .column .field-name-firstname{
            margin-right: 0;
        }
    }
</style>
