<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="quick-access-container">
    <div class="quick-access">
        <form class="form minisearch" id="search_mini_form" action="<?php echo $helper->getResultUrl() ?>" method="get">

            <div class="field search form-search">
                <div class="search__field-wrapper">
                    <input id="search_stiky"
                           data-mage-init='{"quickSearch":{
                        "formSelector":"#search_mini_form_stiky",
                        "url":"<?= /* @escapeNotVerified */
                           $helper->getSuggestUrl() ?>",
                        "destinationSelector":"#search_autocomplete"}
                   }'
                           type="search" hidden
                           name="<?= /* @escapeNotVerified */
                           $helper->getQueryParamName() ?>"
                           value="<?= /* @escapeNotVerified */
                           $helper->getEscapedQueryText() ?>"
                           placeholder="<?= /* @escapeNotVerified */
                           __('What are you looking for?') ?>"
                           class="search__input"
                           maxlength="<?= /* @escapeNotVerified */
                           $helper->getMaxQueryLength() ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div ><?= $block->getChildHtml() ?> </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
   {
      "*": {
              "Walan_Theme/js/customjs/hover": {}
         }
    }
</script>