<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Magento\Customer\Block\Account\Customer $block */
?>
<?php if($block->customerLoggedIn()): ?>
    <li class="customer-welcome">
        <a href="<?= $block->getUrl('customer/account/'); ?>" title="<?= __('Personal area'); ?>">
            <div class="info__icon bm-icon-user"></div>
            <div class="info__title"><?= __('Personal Area') ?></div>
        </a>
    </li>
<?php else: ?>
    <li class="customer-welcome">
        <a href="<?= $block->getUrl('customer/account/login/'); ?>" title="<?= __('Login'); ?>">
            <span class="info__title customer-name">
                <div class="info__icon bm-icon-user"></div>
                <div class="info__title"><?= __('Login/Registration'); ?></div>
            </span>
        </a>
    </li>
<?php endif; ?>
